version: "3.9"

services:

  easy-owntracks:

    image: test #docker.io/owntracks/easy-owntracks

    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443

    volumes:
      - type: bind
        source: ./owntracks-storage
        target: /owntracks-storage
        bind:
          create_host_path: true

    restart: unless-stopped
